tabs -> spaces

diff --git a/bin/execwrapper b/bin/execwrapper
--- a/bin/execwrapper
+++ b/bin/execwrapper
@@ -1,74 +1,74 @@
 #!/bin/sh
 
 [ ! "$3" ] && {
-	echo "Usage: `basename $0` <lockfile> <logfile> [-l] [-t <n>] <cmd>"
-	exit 13
+    echo "Usage: `basename $0` <lockfile> <logfile> [-l] [-t <n>] <cmd>"
+    exit 13
 }
 
 setlock () {
-        local lockfile=$1
-	local host pid lock ret
+    local lockfile=$1
+    local host pid lock ret
 
-	local myhost=`hostname -s`
+    local myhost=`hostname -s`
 
-	# set lock
-	echo "$myhost $$" > ${lockfile}.${myhost}_$$
+    # set lock
+    echo "$myhost $$" > ${lockfile}.${myhost}_$$
 
-	# check count of locks 
-	if [ `ls $lockfile.* | wc -l` -eq 1 ]; then
-		# if we have one==our lock
-		return 0
-	fi
+    # check count of locks 
+    if [ `ls $lockfile.* | wc -l` -eq 1 ]; then
+        # if we have one==our lock
+        return 0
+    fi
 
-	rmlock $lockfile
+    rmlock $lockfile
 
-	# clean old lock
-	local locks="`ls $lockfile.$myhost* 2>/dev/null`"
+    # clean old lock
+    local locks="`ls $lockfile.$myhost* 2>/dev/null`"
 
-	local lockdir=`dirname $lockfile`
+    local lockdir=`dirname $lockfile`
 
-	for lock in $locks; do
-		if [ -f $lock ]; then
-			read host pid < $lock
+    for lock in $locks; do
+        if [ -f $lock ]; then
+            read host pid < $lock
 
-			kill -0 $pid >/dev/null 2>&1
-			if [ $? -ne 0 ]; then
-				rm $lock
-			fi
-		fi
-	done
+            kill -0 $pid >/dev/null 2>&1
+            if [ $? -ne 0 ]; then
+                rm $lock
+            fi
+        fi
+    done
 
-	return 1
+    return 1
 }
 
 rmlock () {
         local lockfile=$1
 
-#	rm -f $lockfile
-	# clean our lock
-	rm -f $lockfile.`hostname -s`_$$
+#   rm -f $lockfile
+    # clean our lock
+    rm -f $lockfile.`hostname -s`_$$
 }
 
 lockfile=$1; shift
 logfile=$1; shift
 
 if [ "$1" = "-l" ]; then
-	warnlock="YES"
-	shift
+    warnlock="YES"
+    shift
 fi
 
 if [ "$1" = "-t" ]; then
-	shift
-	/bin/bash -c "sleep \$((\$RANDOM/$1))"
-	shift
+    shift
+    /bin/bash -c "sleep \$((\$RANDOM/$1))"
+    shift
 fi
 
 setlock $lockfile
 if [ $? -ne 0 ]; then
-	if [ "$warnlock" ]; then
-		echo "- INFO($$) `date`: lockfile $lockfile already exist"
-	fi
-	exit 0
+    if [ "$warnlock" ]; then
+        echo "- INFO($$) `date`: lockfile $lockfile already exist"
+    fi
+    exit 0
 fi
 
 logfilesize=0
@@ -87,13 +87,13 @@ echo "- STOP($$): `date` duration $tdelta sec. Exit code $ret"
 
 case $ret in
 0)
-	;;
+    ;;
 14)
-	;;
+    ;;
 *)
-	echo "`date` ERROR($$): exit code $ret";
-	dd if=$logfile bs=1 skip=$logfilesize 2>/dev/null | tail -n 100 
-	;;
+    echo "`date` ERROR($$): exit code $ret";
+    dd if=$logfile bs=1 skip=$logfilesize 2>/dev/null | tail -n 100 
+    ;;
 esac
 
 rmlock $lockfile
